---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.11"
    hooks:
      - id: ruff-format
        args: ["--check"]
      - id: ruff-check

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: "v1.1.390"
    hooks:
      - id: pyright
        additional_dependencies:
          - deprecation>=2.1.0
          - pytest>=8.0.0

  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.33.0"
    hooks:
      - id: yamllint
